vpc_cird_block = "10.0.0.0/16"
subenet_cird_block = "10.0.0.0/24"
availability_zone = "us-west-2a"
env_prefix = "dev"
instance_type = "t2.micro"
public_key_location = "/Users/ravindu/.ssh/id_rsa.pub"
private_key_location = "/Users/ravindu/.ssh/id_rsa"
remote_entry_script = "/home/ec2-user/entry-script.sh"